fastlane_version "2.27.0"

default_platform :ios

lane :test do
  cocoapods(
  	repo_update: true
  )

  scan(
    device: "iPad Air",
    scheme: "SKCollectionViewDataSource",
    workspace: "SKCollectionViewDataSource.xcworkspace"
  )
end
